stages:
  - build

build:
  stage: build
  tags:
    - openwrt
  image:
    name: mklhub.azurecr.io/rnd/common/openwrt-builder:latest
    entrypoint: [""]
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ./build config-VPU.seed
  only:
    - ci-tests
  artifacts:
    when: always
    paths:
      - bin/
    expire_in: 1 day
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - dl
      - feeds
      - staging_dir
